

workdir: workflow.current_basedir

configfile: "defaults/config.yaml"

segment = ["l", "m", "s"]

# Species names should contain no spaces and instead "_"
species= [
    "andv",
    "htnv",
    "seov",
    "tulv",
    "puuv"
]

include: "rules/prepare_sequences.smk"
include: "rules/construct_phylogeny.smk"
include: "rules/annotate_phylogeny.smk"
include: "rules/export.smk"

rule all:
    input:
        expand("auspice/hantavirus_{species}_{segment}.json", segment=segment, species=species),


if "custom_rules" in config:
    for rule_file in config["custom_rules"]:
        include: rule_file


rule clean:
    shell:
        "rm -rf results auspice"

rule clean_all:
    shell:
        "rm -rf results data .snakemake benchmarks auspice logs"
