# This configuration file should contain all required configuration parameters
# for the ingest workflow to run with additional Nextstrain automation rules.

# Custom rules to run as part of the Nextstrain automated workflow
# The paths should be relative to the ingest directory.
custom_rules:
  - build-configs/nextstrain-automation/upload.smk

# Nextstrain CloudFront domain to ensure that we invalidate CloudFront after the S3 uploads
# This is required as long as we are using the AWS CLI for uploads
cloudfront_domain: "data.nextstrain.org"

# Nextstrain AWS S3 Bucket with pathogen prefix
# Replace <pathogen> with the pathogen repo name.
s3_dst: "s3://nextstrain-data/files/workflows/hantavirus"

# Mapping of files to upload.
# Keys here are the target S3 key (after combining with "s3_dst")
# Values are the local files produced by the workflow
files_to_upload:
  # hantanense
  htnv/l/metadata.tsv.zst: results/htnv/l/metadata.tsv
  htnv/l/sequences.fasta.zst: results/htnv/l/sequences.fasta
  htnv/m/metadata.tsv.zst: results/htnv/m/metadata.tsv
  htnv/m/sequences.fasta.zst: results/htnv/m/sequences.fasta
  htnv/s/metadata.tsv.zst: results/htnv/s/metadata.tsv
  htnv/s/sequences.fasta.zst: results/htnv/s/sequences.fasta
  # puumalaense
  puuv/l/metadata.tsv.zst: results/puuv/l/metadata.tsv
  puuv/l/sequences.fasta.zst: results/puuv/l/sequences.fasta
  puuv/m/metadata.tsv.zst: results/puuv/m/metadata.tsv
  puuv/m/sequences.fasta.zst: results/puuv/m/sequences.fasta
  puuv/s/metadata.tsv.zst: results/puuv/s/metadata.tsv
  puuv/s/sequences.fasta.zst: results/puuv/s/sequences.fasta
  # seoulense
  seov/l/metadata.tsv.zst: results/seov/l/metadata.tsv
  seov/l/sequences.fasta.zst: results/seov/l/sequences.fasta
  seov/m/metadata.tsv.zst: results/seov/m/metadata.tsv
  seov/m/sequences.fasta.zst: results/seov/m/sequences.fasta
  seov/s/metadata.tsv.zst: results/seov/s/metadata.tsv
  seov/s/sequences.fasta.zst: results/seov/s/sequences.fasta
  # tulaense
  tulv/l/metadata.tsv.zst: results/tulv/l/metadata.tsv
  tulv/l/sequences.fasta.zst: results/tulv/l/sequences.fasta
  tulv/m/metadata.tsv.zst: results/tulv/m/metadata.tsv
  tulv/m/sequences.fasta.zst: results/tulv/m/sequences.fasta
  tulv/s/metadata.tsv.zst: results/tulv/s/metadata.tsv
  tulv/s/sequences.fasta.zst: results/tulv/s/sequences.fasta
  # andes open
  andv/l/metadata.tsv.zst: results/andv/l/metadata_open.tsv
  andv/l/sequences.fasta.zst: results/andv/l/sequences_open.fasta
  andv/m/metadata.tsv.zst: results/andv/m/metadata_open.tsv
  andv/m/sequences.fasta.zst: results/andv/m/sequences_open.fasta
  andv/s/metadata.tsv.zst: results/andv/s/metadata_open.tsv
  andv/s/sequences.fasta.zst: results/andv/s/sequences_open.fasta
  # andes restricted
  andv/l/metadata_restricted.tsv.zst: results/andv/l/metadata_restricted.tsv
  andv/l/sequences_restricted.fasta.zst: results/andv/l/sequences_restricted.fasta
  andv/m/metadata_restricted.tsv.zst: results/andv/m/metadata_restricted.tsv
  andv/m/sequences_restricted.fasta.zst: results/andv/m/sequences_restricted.fasta
  andv/s/metadata_restricted.tsv.zst: results/andv/s/metadata_restricted.tsv
  andv/s/sequences_restricted.fasta.zst: results/andv/s/sequences_restricted.fasta