
filter:
  exclude: "defaults/exclude.txt"
  min_length:
    andv:
      l: 200
      m: 500
      s: 450
    htnv:
      l: 400
      m: 400
      s: 260
    puuv:
      l: 500
      m: 450
      s: 450
    seov:
      l: 600
      m: 300
      s: 450
    tulv:
      l: 350
      m: 400
      s: 500
  max_length:
    andv:
      l: 7000
      m: 4000
      s: 2000
    htnv:
      l: 7000
      m: 4000
      s: 2000
    puuv:
      l: 7000
      m: 4000
      s: 2000
    seov:
      l: 7000
      m: 4000
      s: 2000
    tulv:
      l: 7000
      m: 4000
      s: 2000

strain_id_field: "accession"

ingest_url_prefix: "https://data.nextstrain.org/files/workflows/hantavirus"

full_species_names:
  htnv: "Orthohantavirus_hantanense"
  puuv: "Orthohantavirus_puumalaense"
  seov: "Orthohantavirus_seoulense"
  tulv: "Orthohantavirus_tulaense"

tree:
  method: "iqtree"

refine:
  root: "mid_point"

ancestral:
  inference: "joint"

export:
  auspice_config: "defaults/auspice_config.json"
  description: "defaults/description.md"
  segment_metadata_columns:
    - accession_version
    - length
    - NCBI_species
    - date_released
    - date_updated